# Generated by tools/gen_fx.py
playsound minecraft:block.note_block.chime player @a ~ ~ ~ 0.7 0.75
particle minecraft:dust{color:[0.72,0.45,1],scale:1} ~0.5 ~0.1 ~ 1 0 0 0.18 0
particle minecraft:dust{color:[0.72,0.45,1],scale:1} ~0.476 ~0.1 ~0.155 0.951 0 0.309 0.18 0
particle minecraft:dust{color:[0.72,0.45,1],scale:1} ~0.405 ~0.1 ~0.294 0.809 0 0.588 0.18 0
particle minecraft:dust{color:[0.72,0.45,1],scale:1} ~0.294 ~0.1 ~0.405 0.588 0 0.809 0.18 0
particle minecraft:dust{color:[0.72,0.45,1],scale:1} ~0.155 ~0.1 ~0.476 0.309 0 0.951 0.18 0
particle minecraft:dust{color:[0.72,0.45,1],scale:1} ~ ~0.1 ~0.5 0 0 1 0.18 0
particle minecraft:dust{color:[0.72,0.45,1],scale:1} ~-0.155 ~0.1 ~0.476 -0.309 0 0.951 0.18 0
particle minecraft:dust{color:[0.72,0.45,1],scale:1} ~-0.294 ~0.1 ~0.405 -0.588 0 0.809 0.18 0
particle minecraft:dust{color:[0.72,0.45,1],scale:1} ~-0.405 ~0.1 ~0.294 -0.809 0 0.588 0.18 0
particle minecraft:dust{color:[0.72,0.45,1],scale:1} ~-0.476 ~0.1 ~0.155 -0.951 0 0.309 0.18 0
particle minecraft:dust{color:[0.72,0.45,1],scale:1} ~-0.5 ~0.1 ~ -1 0 0 0.18 0
particle minecraft:dust{color:[0.72,0.45,1],scale:1} ~-0.476 ~0.1 ~-0.155 -0.951 0 -0.309 0.18 0
particle minecraft:dust{color:[0.72,0.45,1],scale:1} ~-0.405 ~0.1 ~-0.294 -0.809 0 -0.588 0.18 0
particle minecraft:dust{color:[0.72,0.45,1],scale:1} ~-0.294 ~0.1 ~-0.405 -0.588 0 -0.809 0.18 0
particle minecraft:dust{color:[0.72,0.45,1],scale:1} ~-0.155 ~0.1 ~-0.476 -0.309 0 -0.951 0.18 0
particle minecraft:dust{color:[0.72,0.45,1],scale:1} ~ ~0.1 ~-0.5 0 0 -1 0.18 0
particle minecraft:dust{color:[0.72,0.45,1],scale:1} ~0.155 ~0.1 ~-0.476 0.309 0 -0.951 0.18 0
particle minecraft:dust{color:[0.72,0.45,1],scale:1} ~0.294 ~0.1 ~-0.405 0.588 0 -0.809 0.18 0
particle minecraft:dust{color:[0.72,0.45,1],scale:1} ~0.405 ~0.1 ~-0.294 0.809 0 -0.588 0.18 0
particle minecraft:dust{color:[0.72,0.45,1],scale:1} ~0.476 ~0.1 ~-0.155 0.951 0 -0.309 0.18 0
particle minecraft:end_rod ~ ~2.8 ~ 0.8 0.2 0.8 0.01 3
particle minecraft:electric_spark ~ ~1 ~ 0.6 0.8 0.6 0.05 2
