# Generated by tools/gen_fx.py
playsound minecraft:block.note_block.chime player @a ~ ~ ~ 0.7 1.26
particle minecraft:end_rod ~ ~2.8 ~ 0.8 0.2 0.8 0.01 3
particle minecraft:electric_spark ~ ~1 ~ 0.6 0.8 0.6 0.05 2
