# Generated by tools/gen_fx.py
function pocket:fx/key_kill
particle minecraft:flash{color:[0.7,0.4,1,1.0]} ~ ~1 ~ 0 0 0 0 1 force
particle minecraft:reverse_portal ~ ~1 ~ 0.2 0.5 0.2 0.35 60
particle minecraft:end_rod ~ ~1 ~ 0 0 0 0.22 30
playsound minecraft:entity.illusioner.mirror_move player @a ~ ~ ~ 1 0.9
playsound minecraft:block.amethyst_cluster.break player @a ~ ~ ~ 1 0.6
playsound minecraft:entity.breeze.wind_burst player @a ~ ~ ~ 0.5 1.5
