# Generated by tools/gen_fx.py
particle minecraft:flash{color:[0.7,0.4,1.0,1.0]} ~ ~0.5 ~ 0 0 0 0 1
particle minecraft:reverse_portal ~ ~0.6 ~ 0.3 0.5 0.3 0.3 50
particle minecraft:end_rod ~0.2 ~0.2 ~ 1 0 0 0.2 0
particle minecraft:end_rod ~0.185 ~0.2 ~0.077 0.924 0 0.383 0.2 0
particle minecraft:end_rod ~0.141 ~0.2 ~0.141 0.707 0 0.707 0.2 0
particle minecraft:end_rod ~0.077 ~0.2 ~0.185 0.383 0 0.924 0.2 0
particle minecraft:end_rod ~ ~0.2 ~0.2 0 0 1 0.2 0
particle minecraft:end_rod ~-0.077 ~0.2 ~0.185 -0.383 0 0.924 0.2 0
particle minecraft:end_rod ~-0.141 ~0.2 ~0.141 -0.707 0 0.707 0.2 0
particle minecraft:end_rod ~-0.185 ~0.2 ~0.077 -0.924 0 0.383 0.2 0
particle minecraft:end_rod ~-0.2 ~0.2 ~ -1 0 0 0.2 0
particle minecraft:end_rod ~-0.185 ~0.2 ~-0.077 -0.924 0 -0.383 0.2 0
particle minecraft:end_rod ~-0.141 ~0.2 ~-0.141 -0.707 0 -0.707 0.2 0
particle minecraft:end_rod ~-0.077 ~0.2 ~-0.185 -0.383 0 -0.924 0.2 0
particle minecraft:end_rod ~ ~0.2 ~-0.2 0 0 -1 0.2 0
particle minecraft:end_rod ~0.077 ~0.2 ~-0.185 0.383 0 -0.924 0.2 0
particle minecraft:end_rod ~0.141 ~0.2 ~-0.141 0.707 0 -0.707 0.2 0
particle minecraft:end_rod ~0.185 ~0.2 ~-0.077 0.924 0 -0.383 0.2 0
playsound minecraft:entity.illusioner.mirror_move neutral @a ~ ~ ~ 1 1.3
playsound minecraft:block.amethyst_cluster.break neutral @a ~ ~ ~ 1 0.9
