# Generated by tools/gen_fx.py
particle minecraft:reverse_portal ~ ~0.6 ~ 0.3 0.5 0.3 0.2 40
particle minecraft:end_rod ~0.2 ~0.15 ~ 1 0 0 0.18 0
particle minecraft:end_rod ~0.185 ~0.15 ~0.077 0.924 0 0.383 0.18 0
particle minecraft:end_rod ~0.141 ~0.15 ~0.141 0.707 0 0.707 0.18 0
particle minecraft:end_rod ~0.077 ~0.15 ~0.185 0.383 0 0.924 0.18 0
particle minecraft:end_rod ~ ~0.15 ~0.2 0 0 1 0.18 0
particle minecraft:end_rod ~-0.077 ~0.15 ~0.185 -0.383 0 0.924 0.18 0
particle minecraft:end_rod ~-0.141 ~0.15 ~0.141 -0.707 0 0.707 0.18 0
particle minecraft:end_rod ~-0.185 ~0.15 ~0.077 -0.924 0 0.383 0.18 0
particle minecraft:end_rod ~-0.2 ~0.15 ~ -1 0 0 0.18 0
particle minecraft:end_rod ~-0.185 ~0.15 ~-0.077 -0.924 0 -0.383 0.18 0
particle minecraft:end_rod ~-0.141 ~0.15 ~-0.141 -0.707 0 -0.707 0.18 0
particle minecraft:end_rod ~-0.077 ~0.15 ~-0.185 -0.383 0 -0.924 0.18 0
particle minecraft:end_rod ~ ~0.15 ~-0.2 0 0 -1 0.18 0
particle minecraft:end_rod ~0.077 ~0.15 ~-0.185 0.383 0 -0.924 0.18 0
particle minecraft:end_rod ~0.141 ~0.15 ~-0.141 0.707 0 -0.707 0.18 0
particle minecraft:end_rod ~0.185 ~0.15 ~-0.077 0.924 0 -0.383 0.18 0
playsound minecraft:block.amethyst_block.chime neutral @a ~ ~ ~ 1 1.2
