# Generated by tools/gen_fx.py
$particle minecraft:trail{target:[$(x),$(y),$(z)],color:[1,1,0.85],duration:12} ~2.763 ~0.1 ~1.168 0 0 0 0 1 force
$particle minecraft:trail{target:[$(x),$(y),$(z)],color:[1,0.8,0.35],duration:12} ~1.128 ~0.1 ~2.78 0 0 0 0 1 force
$particle minecraft:trail{target:[$(x),$(y),$(z)],color:[1,1,0.85],duration:12} ~-1.168 ~0.1 ~2.763 0 0 0 0 1 force
$particle minecraft:trail{target:[$(x),$(y),$(z)],color:[1,0.8,0.35],duration:12} ~-2.78 ~0.1 ~1.128 0 0 0 0 1 force
$particle minecraft:trail{target:[$(x),$(y),$(z)],color:[1,1,0.85],duration:12} ~-2.763 ~0.1 ~-1.168 0 0 0 0 1 force
$particle minecraft:trail{target:[$(x),$(y),$(z)],color:[1,0.8,0.35],duration:12} ~-1.128 ~0.1 ~-2.78 0 0 0 0 1 force
$particle minecraft:trail{target:[$(x),$(y),$(z)],color:[1,1,0.85],duration:12} ~1.168 ~0.1 ~-2.763 0 0 0 0 1 force
$particle minecraft:trail{target:[$(x),$(y),$(z)],color:[1,0.8,0.35],duration:12} ~2.78 ~0.1 ~-1.128 0 0 0 0 1 force
