# Generated by tools/gen_fx.py
execute store result storage pocket:tmp me.x double 0.01 run data get entity @s Pos[0] 100
execute store result score #y pocket.tmp run data get entity @s Pos[1] 100
execute store result storage pocket:tmp me.y double 0.01 run scoreboard players add #y pocket.tmp 120
execute store result storage pocket:tmp me.z double 0.01 run data get entity @s Pos[2] 100
function pocket:fx/streams_in_m with storage pocket:tmp me
