# Generated by tools/gen_fx.py
$particle minecraft:trail{target:[$(x),$(y),$(z)],color:[0.35,0.9,1],duration:12} ~3 ~0.1 ~ 0 0 0 0 1 force
$particle minecraft:trail{target:[$(x),$(y),$(z)],color:[0.62,0.32,1],duration:12} ~2.121 ~0.1 ~2.121 0 0 0 0 1 force
$particle minecraft:trail{target:[$(x),$(y),$(z)],color:[0.35,0.9,1],duration:12} ~ ~0.1 ~3 0 0 0 0 1 force
$particle minecraft:trail{target:[$(x),$(y),$(z)],color:[0.62,0.32,1],duration:12} ~-2.121 ~0.1 ~2.121 0 0 0 0 1 force
$particle minecraft:trail{target:[$(x),$(y),$(z)],color:[0.35,0.9,1],duration:12} ~-3 ~0.1 ~ 0 0 0 0 1 force
$particle minecraft:trail{target:[$(x),$(y),$(z)],color:[0.62,0.32,1],duration:12} ~-2.121 ~0.1 ~-2.121 0 0 0 0 1 force
$particle minecraft:trail{target:[$(x),$(y),$(z)],color:[0.35,0.9,1],duration:12} ~ ~0.1 ~-3 0 0 0 0 1 force
$particle minecraft:trail{target:[$(x),$(y),$(z)],color:[0.62,0.32,1],duration:12} ~2.121 ~0.1 ~-2.121 0 0 0 0 1 force
