# Generated by tools/gen_fx.py
particle minecraft:dust_color_transition{from_color:[1,0.8,0.35],to_color:[1,1,0.85],scale:0.9} ~0.367 ~1.313 ~0.836 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[1,0.8,0.35],to_color:[1,1,0.85],scale:0.9} ~-0.367 ~1.313 ~-0.836 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[1,0.8,0.35],to_color:[1,1,0.85],scale:0.9} ~0.186 ~1.282 ~0.887 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[1,0.8,0.35],to_color:[1,1,0.85],scale:0.9} ~-0.186 ~1.282 ~-0.887 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[1,0.8,0.35],to_color:[1,1,0.85],scale:0.9} ~ ~1.25 ~0.9 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[1,0.8,0.35],to_color:[1,1,0.85],scale:0.9} ~ ~1.25 ~-0.9 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[1,0.8,0.35],to_color:[1,1,0.85],scale:0.9} ~-0.183 ~1.218 ~0.874 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[1,0.8,0.35],to_color:[1,1,0.85],scale:0.9} ~0.183 ~1.218 ~-0.874 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~0.963 ~0.06 ~1.214 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~0.426 ~0.06 ~1.49 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~-0.177 ~0.06 ~1.54 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~-0.753 ~0.06 ~1.355 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~-1.214 ~0.06 ~0.963 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~-1.49 ~0.06 ~0.426 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~-1.54 ~0.06 ~-0.177 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~-1.355 ~0.06 ~-0.753 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~-0.963 ~0.06 ~-1.214 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~-0.426 ~0.06 ~-1.49 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~0.177 ~0.06 ~-1.54 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~0.753 ~0.06 ~-1.355 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~1.214 ~0.06 ~-0.963 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~1.49 ~0.06 ~-0.426 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~1.54 ~0.06 ~0.177 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~1.355 ~0.06 ~0.753 0 0 0 0 1
particle minecraft:dust{color:[1,0.95,0.7],scale:0.5} ~0.153 ~0.06 ~-0.887 0 0 0 0 1
particle minecraft:dust{color:[1,0.95,0.7],scale:0.5} ~0.735 ~0.06 ~-0.519 0 0 0 0 1
particle minecraft:dust{color:[1,0.95,0.7],scale:0.5} ~0.887 ~0.06 ~0.153 0 0 0 0 1
particle minecraft:dust{color:[1,0.95,0.7],scale:0.5} ~0.519 ~0.06 ~0.735 0 0 0 0 1
particle minecraft:dust{color:[1,0.95,0.7],scale:0.5} ~-0.153 ~0.06 ~0.887 0 0 0 0 1
particle minecraft:dust{color:[1,0.95,0.7],scale:0.5} ~-0.735 ~0.06 ~0.519 0 0 0 0 1
particle minecraft:dust{color:[1,0.95,0.7],scale:0.5} ~-0.887 ~0.06 ~-0.153 0 0 0 0 1
particle minecraft:dust{color:[1,0.95,0.7],scale:0.5} ~-0.519 ~0.06 ~-0.735 0 0 0 0 1
particle minecraft:enchant ~ ~1.1 ~ 0.4 0.4 0.4 1.6 4
particle minecraft:portal ~ ~0.9 ~ 0.5 0.6 0.5 1.0 6
function pocket:fx/streams_out
playsound minecraft:block.portal.trigger player @s ~ ~ ~ 0.35 1.6
