# Generated by tools/gen_fx.py
particle minecraft:dust_color_transition{from_color:[1,0.8,0.35],to_color:[1,1,0.85],scale:0.9} ~-0.814 ~1.061 ~0.279 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[1,0.8,0.35],to_color:[1,1,0.85],scale:0.9} ~0.814 ~1.061 ~-0.279 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[1,0.8,0.35],to_color:[1,1,0.85],scale:0.9} ~-0.847 ~1.029 ~0.106 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[1,0.8,0.35],to_color:[1,1,0.85],scale:0.9} ~0.847 ~1.029 ~-0.106 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[1,0.8,0.35],to_color:[1,1,0.85],scale:0.9} ~-0.844 ~0.997 ~-0.07 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[1,0.8,0.35],to_color:[1,1,0.85],scale:0.9} ~0.844 ~0.997 ~0.07 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[1,0.8,0.35],to_color:[1,1,0.85],scale:0.9} ~-0.806 ~0.966 ~-0.24 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[1,0.8,0.35],to_color:[1,1,0.85],scale:0.9} ~0.806 ~0.966 ~0.24 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~0.731 ~0.06 ~1.367 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~0.152 ~0.06 ~1.543 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~-0.45 ~0.06 ~1.483 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~-0.983 ~0.06 ~1.198 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~-1.367 ~0.06 ~0.731 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~-1.543 ~0.06 ~0.152 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~-1.483 ~0.06 ~-0.45 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~-1.198 ~0.06 ~-0.983 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~-0.731 ~0.06 ~-1.367 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~-0.152 ~0.06 ~-1.543 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~0.45 ~0.06 ~-1.483 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~0.983 ~0.06 ~-1.198 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~1.367 ~0.06 ~-0.731 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~1.543 ~0.06 ~-0.152 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~1.483 ~0.06 ~0.45 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~1.198 ~0.06 ~0.983 0 0 0 0 1
particle minecraft:dust{color:[1,0.95,0.7],scale:0.5} ~-0.098 ~0.06 ~-0.895 0 0 0 0 1
particle minecraft:dust{color:[1,0.95,0.7],scale:0.5} ~0.563 ~0.06 ~-0.702 0 0 0 0 1
particle minecraft:dust{color:[1,0.95,0.7],scale:0.5} ~0.895 ~0.06 ~-0.098 0 0 0 0 1
particle minecraft:dust{color:[1,0.95,0.7],scale:0.5} ~0.702 ~0.06 ~0.563 0 0 0 0 1
particle minecraft:dust{color:[1,0.95,0.7],scale:0.5} ~0.098 ~0.06 ~0.895 0 0 0 0 1
particle minecraft:dust{color:[1,0.95,0.7],scale:0.5} ~-0.563 ~0.06 ~0.702 0 0 0 0 1
particle minecraft:dust{color:[1,0.95,0.7],scale:0.5} ~-0.895 ~0.06 ~0.098 0 0 0 0 1
particle minecraft:dust{color:[1,0.95,0.7],scale:0.5} ~-0.702 ~0.06 ~-0.563 0 0 0 0 1
particle minecraft:enchant ~ ~1.1 ~ 0.4 0.4 0.4 1.6 4
particle minecraft:portal ~ ~0.9 ~ 0.5 0.6 0.5 1.0 6
posteffect add @s minecraft:blur
execute as @e[type=minecraft:item_display,tag=pocket.fxkey,distance=..6] if score @s pocket.slot = #s pocket.tmp run data merge entity @s {start_interpolation:0,interpolation_duration:2,transformation:{left_rotation:{angle:6.283f,axis:[0f,1f,0f]},right_rotation:[0f,0f,0f,1f],translation:[0f,0f,0f],scale:[1.05f,1.05f,1.05f]}}
