# Generated by tools/gen_fx.py
particle minecraft:dust_color_transition{from_color:[1,0.8,0.35],to_color:[1,1,0.85],scale:0.9} ~-0.198 ~0.808 ~-0.783 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[1,0.8,0.35],to_color:[1,1,0.85],scale:0.9} ~0.198 ~0.808 ~0.783 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[1,0.8,0.35],to_color:[1,1,0.85],scale:0.9} ~-0.033 ~0.776 ~-0.801 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[1,0.8,0.35],to_color:[1,1,0.85],scale:0.9} ~0.033 ~0.776 ~0.801 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[1,0.8,0.35],to_color:[1,1,0.85],scale:0.9} ~0.131 ~0.745 ~-0.784 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[1,0.8,0.35],to_color:[1,1,0.85],scale:0.9} ~-0.131 ~0.745 ~0.784 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[1,0.8,0.35],to_color:[1,1,0.85],scale:0.9} ~0.287 ~0.713 ~-0.734 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[1,0.8,0.35],to_color:[1,1,0.85],scale:0.9} ~-0.287 ~0.713 ~0.734 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~0.474 ~0.06 ~1.476 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~-0.127 ~0.06 ~1.545 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~-0.708 ~0.06 ~1.379 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~-1.182 ~0.06 ~1.003 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~-1.476 ~0.06 ~0.474 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~-1.545 ~0.06 ~-0.127 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~-1.379 ~0.06 ~-0.708 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~-1.003 ~0.06 ~-1.182 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~-0.474 ~0.06 ~-1.476 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~0.127 ~0.06 ~-1.545 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~0.708 ~0.06 ~-1.379 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~1.182 ~0.06 ~-1.003 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~1.476 ~0.06 ~-0.474 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~1.545 ~0.06 ~0.127 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~1.379 ~0.06 ~0.708 0 0 0 0 1
particle minecraft:dust{color:[1,0.75,0.3],scale:0.6} ~1.003 ~0.06 ~1.182 0 0 0 0 1
particle minecraft:dust{color:[1,0.95,0.7],scale:0.5} ~-0.342 ~0.06 ~-0.833 0 0 0 0 1
particle minecraft:dust{color:[1,0.95,0.7],scale:0.5} ~0.347 ~0.06 ~-0.83 0 0 0 0 1
particle minecraft:dust{color:[1,0.95,0.7],scale:0.5} ~0.833 ~0.06 ~-0.342 0 0 0 0 1
particle minecraft:dust{color:[1,0.95,0.7],scale:0.5} ~0.83 ~0.06 ~0.347 0 0 0 0 1
particle minecraft:dust{color:[1,0.95,0.7],scale:0.5} ~0.342 ~0.06 ~0.833 0 0 0 0 1
particle minecraft:dust{color:[1,0.95,0.7],scale:0.5} ~-0.347 ~0.06 ~0.83 0 0 0 0 1
particle minecraft:dust{color:[1,0.95,0.7],scale:0.5} ~-0.833 ~0.06 ~0.342 0 0 0 0 1
particle minecraft:dust{color:[1,0.95,0.7],scale:0.5} ~-0.83 ~0.06 ~-0.347 0 0 0 0 1
particle minecraft:enchant ~ ~1.1 ~ 0.4 0.4 0.4 1.6 4
particle minecraft:portal ~ ~0.9 ~ 0.5 0.6 0.5 1.0 6
function pocket:fx/streams_out
execute as @e[type=minecraft:item_display,tag=pocket.fxkey,distance=..6] if score @s pocket.slot = #s pocket.tmp run data merge entity @s {start_interpolation:0,interpolation_duration:2,transformation:{left_rotation:{angle:1.571f,axis:[0f,1f,0f]},right_rotation:[0f,0f,0f,1f],translation:[0f,0f,0f],scale:[1.15f,1.15f,1.15f]}}
