# Generated by tools/gen_fx.py
particle minecraft:dust_color_transition{from_color:[0.62,0.32,1],to_color:[0.35,0.9,1],scale:0.9} ~1.15 ~0.05 ~ 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[0.62,0.32,1],to_color:[0.35,0.9,1],scale:0.9} ~-1.15 ~0.05 ~ 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[0.62,0.32,1],to_color:[0.35,0.9,1],scale:0.9} ~1.119 ~0.082 ~0.235 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[0.62,0.32,1],to_color:[0.35,0.9,1],scale:0.9} ~-1.119 ~0.082 ~-0.235 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[0.62,0.32,1],to_color:[0.35,0.9,1],scale:0.9} ~1.041 ~0.113 ~0.457 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[0.62,0.32,1],to_color:[0.35,0.9,1],scale:0.9} ~-1.041 ~0.113 ~-0.457 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[0.62,0.32,1],to_color:[0.35,0.9,1],scale:0.9} ~0.92 ~0.145 ~0.657 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[0.62,0.32,1],to_color:[0.35,0.9,1],scale:0.9} ~-0.92 ~0.145 ~-0.657 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~1.544 ~0.06 ~0.139 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~1.373 ~0.06 ~0.719 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~0.993 ~0.06 ~1.19 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~0.462 ~0.06 ~1.48 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~-0.139 ~0.06 ~1.544 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~-0.719 ~0.06 ~1.373 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~-1.19 ~0.06 ~0.993 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~-1.48 ~0.06 ~0.462 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~-1.544 ~0.06 ~-0.139 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~-1.373 ~0.06 ~-0.719 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~-0.993 ~0.06 ~-1.19 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~-0.462 ~0.06 ~-1.48 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~0.139 ~0.06 ~-1.544 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~0.719 ~0.06 ~-1.373 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~1.19 ~0.06 ~-0.993 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~1.48 ~0.06 ~-0.462 0 0 0 0 1
particle minecraft:dust{color:[0.4,0.75,1],scale:0.5} ~0.891 ~0.06 ~-0.126 0 0 0 0 1
particle minecraft:dust{color:[0.4,0.75,1],scale:0.5} ~0.719 ~0.06 ~0.541 0 0 0 0 1
particle minecraft:dust{color:[0.4,0.75,1],scale:0.5} ~0.126 ~0.06 ~0.891 0 0 0 0 1
particle minecraft:dust{color:[0.4,0.75,1],scale:0.5} ~-0.541 ~0.06 ~0.719 0 0 0 0 1
particle minecraft:dust{color:[0.4,0.75,1],scale:0.5} ~-0.891 ~0.06 ~0.126 0 0 0 0 1
particle minecraft:dust{color:[0.4,0.75,1],scale:0.5} ~-0.719 ~0.06 ~-0.541 0 0 0 0 1
particle minecraft:dust{color:[0.4,0.75,1],scale:0.5} ~-0.126 ~0.06 ~-0.891 0 0 0 0 1
particle minecraft:dust{color:[0.4,0.75,1],scale:0.5} ~0.541 ~0.06 ~-0.719 0 0 0 0 1
particle minecraft:enchant ~ ~1.1 ~ 0.4 0.4 0.4 1.6 4
particle minecraft:portal ~ ~0.9 ~ 0.5 0.6 0.5 1.0 6
function pocket:fx/key_spawn
playsound minecraft:block.beacon.activate player @a ~ ~ ~ 0.7 1.7
playsound minecraft:block.trial_spawner.ominous_activate player @a ~ ~ ~ 0.5 1.4
playsound minecraft:block.respawn_anchor.charge player @a ~ ~ ~ 0.6 0.8
