# Generated by tools/gen_fx.py
particle minecraft:dust_color_transition{from_color:[0.62,0.32,1],to_color:[0.35,0.9,1],scale:0.9} ~-0.814 ~1.439 ~0.279 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[0.62,0.32,1],to_color:[0.35,0.9,1],scale:0.9} ~0.814 ~1.439 ~-0.279 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[0.62,0.32,1],to_color:[0.35,0.9,1],scale:0.9} ~-0.847 ~1.471 ~0.106 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[0.62,0.32,1],to_color:[0.35,0.9,1],scale:0.9} ~0.847 ~1.471 ~-0.106 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[0.62,0.32,1],to_color:[0.35,0.9,1],scale:0.9} ~-0.844 ~1.503 ~-0.07 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[0.62,0.32,1],to_color:[0.35,0.9,1],scale:0.9} ~0.844 ~1.503 ~0.07 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[0.62,0.32,1],to_color:[0.35,0.9,1],scale:0.9} ~-0.806 ~1.534 ~-0.24 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[0.62,0.32,1],to_color:[0.35,0.9,1],scale:0.9} ~0.806 ~1.534 ~0.24 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~0.731 ~0.06 ~1.367 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~0.152 ~0.06 ~1.543 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~-0.45 ~0.06 ~1.483 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~-0.983 ~0.06 ~1.198 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~-1.367 ~0.06 ~0.731 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~-1.543 ~0.06 ~0.152 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~-1.483 ~0.06 ~-0.45 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~-1.198 ~0.06 ~-0.983 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~-0.731 ~0.06 ~-1.367 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~-0.152 ~0.06 ~-1.543 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~0.45 ~0.06 ~-1.483 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~0.983 ~0.06 ~-1.198 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~1.367 ~0.06 ~-0.731 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~1.543 ~0.06 ~-0.152 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~1.483 ~0.06 ~0.45 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~1.198 ~0.06 ~0.983 0 0 0 0 1
particle minecraft:dust{color:[0.4,0.75,1],scale:0.5} ~-0.098 ~0.06 ~-0.895 0 0 0 0 1
particle minecraft:dust{color:[0.4,0.75,1],scale:0.5} ~0.563 ~0.06 ~-0.702 0 0 0 0 1
particle minecraft:dust{color:[0.4,0.75,1],scale:0.5} ~0.895 ~0.06 ~-0.098 0 0 0 0 1
particle minecraft:dust{color:[0.4,0.75,1],scale:0.5} ~0.702 ~0.06 ~0.563 0 0 0 0 1
particle minecraft:dust{color:[0.4,0.75,1],scale:0.5} ~0.098 ~0.06 ~0.895 0 0 0 0 1
particle minecraft:dust{color:[0.4,0.75,1],scale:0.5} ~-0.563 ~0.06 ~0.702 0 0 0 0 1
particle minecraft:dust{color:[0.4,0.75,1],scale:0.5} ~-0.895 ~0.06 ~0.098 0 0 0 0 1
particle minecraft:dust{color:[0.4,0.75,1],scale:0.5} ~-0.702 ~0.06 ~-0.563 0 0 0 0 1
particle minecraft:enchant ~ ~1.1 ~ 0.4 0.4 0.4 1.6 4
particle minecraft:portal ~ ~0.9 ~ 0.5 0.6 0.5 1.0 6
posteffect add @s minecraft:blur
execute as @e[type=minecraft:item_display,tag=pocket.fxkey,distance=..6] if score @s pocket.slot = #s pocket.tmp run data merge entity @s {start_interpolation:0,interpolation_duration:2,transformation:{left_rotation:{angle:6.283f,axis:[0f,1f,0f]},right_rotation:[0f,0f,0f,1f],translation:[0f,0f,0f],scale:[1.05f,1.05f,1.05f]}}
