# Generated by tools/gen_fx.py
particle minecraft:dust_color_transition{from_color:[0.62,0.32,1],to_color:[0.35,0.9,1],scale:0.9} ~-0.198 ~1.692 ~-0.783 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[0.62,0.32,1],to_color:[0.35,0.9,1],scale:0.9} ~0.198 ~1.692 ~0.783 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[0.62,0.32,1],to_color:[0.35,0.9,1],scale:0.9} ~-0.033 ~1.724 ~-0.801 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[0.62,0.32,1],to_color:[0.35,0.9,1],scale:0.9} ~0.033 ~1.724 ~0.801 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[0.62,0.32,1],to_color:[0.35,0.9,1],scale:0.9} ~0.131 ~1.755 ~-0.784 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[0.62,0.32,1],to_color:[0.35,0.9,1],scale:0.9} ~-0.131 ~1.755 ~0.784 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[0.62,0.32,1],to_color:[0.35,0.9,1],scale:0.9} ~0.287 ~1.787 ~-0.734 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[0.62,0.32,1],to_color:[0.35,0.9,1],scale:0.9} ~-0.287 ~1.787 ~0.734 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~0.474 ~0.06 ~1.476 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~-0.127 ~0.06 ~1.545 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~-0.708 ~0.06 ~1.379 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~-1.182 ~0.06 ~1.003 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~-1.476 ~0.06 ~0.474 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~-1.545 ~0.06 ~-0.127 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~-1.379 ~0.06 ~-0.708 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~-1.003 ~0.06 ~-1.182 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~-0.474 ~0.06 ~-1.476 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~0.127 ~0.06 ~-1.545 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~0.708 ~0.06 ~-1.379 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~1.182 ~0.06 ~-1.003 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~1.476 ~0.06 ~-0.474 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~1.545 ~0.06 ~0.127 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~1.379 ~0.06 ~0.708 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~1.003 ~0.06 ~1.182 0 0 0 0 1
particle minecraft:dust{color:[0.4,0.75,1],scale:0.5} ~-0.342 ~0.06 ~-0.833 0 0 0 0 1
particle minecraft:dust{color:[0.4,0.75,1],scale:0.5} ~0.347 ~0.06 ~-0.83 0 0 0 0 1
particle minecraft:dust{color:[0.4,0.75,1],scale:0.5} ~0.833 ~0.06 ~-0.342 0 0 0 0 1
particle minecraft:dust{color:[0.4,0.75,1],scale:0.5} ~0.83 ~0.06 ~0.347 0 0 0 0 1
particle minecraft:dust{color:[0.4,0.75,1],scale:0.5} ~0.342 ~0.06 ~0.833 0 0 0 0 1
particle minecraft:dust{color:[0.4,0.75,1],scale:0.5} ~-0.347 ~0.06 ~0.83 0 0 0 0 1
particle minecraft:dust{color:[0.4,0.75,1],scale:0.5} ~-0.833 ~0.06 ~0.342 0 0 0 0 1
particle minecraft:dust{color:[0.4,0.75,1],scale:0.5} ~-0.83 ~0.06 ~-0.347 0 0 0 0 1
particle minecraft:enchant ~ ~1.1 ~ 0.4 0.4 0.4 1.6 4
particle minecraft:portal ~ ~0.9 ~ 0.5 0.6 0.5 1.0 6
function pocket:fx/streams_in
execute as @e[type=minecraft:item_display,tag=pocket.fxkey,distance=..6] if score @s pocket.slot = #s pocket.tmp run data merge entity @s {start_interpolation:0,interpolation_duration:2,transformation:{left_rotation:{angle:1.571f,axis:[0f,1f,0f]},right_rotation:[0f,0f,0f,1f],translation:[0f,0f,0f],scale:[1.15f,1.15f,1.15f]}}
