# Generated by tools/gen_fx.py
particle minecraft:dust_color_transition{from_color:[0.62,0.32,1],to_color:[0.35,0.9,1],scale:0.9} ~0.745 ~1.945 ~-0.124 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[0.62,0.32,1],to_color:[0.35,0.9,1],scale:0.9} ~-0.745 ~1.945 ~0.124 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[0.62,0.32,1],to_color:[0.35,0.9,1],scale:0.9} ~0.748 ~1.976 ~0.031 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[0.62,0.32,1],to_color:[0.35,0.9,1],scale:0.9} ~-0.748 ~1.976 ~-0.031 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[0.62,0.32,1],to_color:[0.35,0.9,1],scale:0.9} ~0.719 ~2.008 ~0.182 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[0.62,0.32,1],to_color:[0.35,0.9,1],scale:0.9} ~-0.719 ~2.008 ~-0.182 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[0.62,0.32,1],to_color:[0.35,0.9,1],scale:0.9} ~0.661 ~2.039 ~0.323 0 0 0 0 1
particle minecraft:dust_color_transition{from_color:[0.62,0.32,1],to_color:[0.35,0.9,1],scale:0.9} ~-0.661 ~2.039 ~-0.323 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~0.202 ~0.06 ~1.537 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~-0.401 ~0.06 ~1.497 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~-0.944 ~0.06 ~1.23 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~-1.342 ~0.06 ~0.775 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~-1.537 ~0.06 ~0.202 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~-1.497 ~0.06 ~-0.401 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~-1.23 ~0.06 ~-0.944 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~-0.775 ~0.06 ~-1.342 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~-0.202 ~0.06 ~-1.537 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~0.401 ~0.06 ~-1.497 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~0.944 ~0.06 ~-1.23 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~1.342 ~0.06 ~-0.775 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~1.537 ~0.06 ~-0.202 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~1.497 ~0.06 ~0.401 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~1.23 ~0.06 ~0.944 0 0 0 0 1
particle minecraft:dust{color:[0.72,0.45,1],scale:0.6} ~0.775 ~0.06 ~1.342 0 0 0 0 1
particle minecraft:dust{color:[0.4,0.75,1],scale:0.5} ~-0.558 ~0.06 ~-0.706 0 0 0 0 1
particle minecraft:dust{color:[0.4,0.75,1],scale:0.5} ~0.104 ~0.06 ~-0.894 0 0 0 0 1
particle minecraft:dust{color:[0.4,0.75,1],scale:0.5} ~0.706 ~0.06 ~-0.558 0 0 0 0 1
particle minecraft:dust{color:[0.4,0.75,1],scale:0.5} ~0.894 ~0.06 ~0.104 0 0 0 0 1
particle minecraft:dust{color:[0.4,0.75,1],scale:0.5} ~0.558 ~0.06 ~0.706 0 0 0 0 1
particle minecraft:dust{color:[0.4,0.75,1],scale:0.5} ~-0.104 ~0.06 ~0.894 0 0 0 0 1
particle minecraft:dust{color:[0.4,0.75,1],scale:0.5} ~-0.706 ~0.06 ~0.558 0 0 0 0 1
particle minecraft:dust{color:[0.4,0.75,1],scale:0.5} ~-0.894 ~0.06 ~-0.104 0 0 0 0 1
particle minecraft:enchant ~ ~1.1 ~ 0.4 0.4 0.4 1.6 4
particle minecraft:portal ~ ~0.9 ~ 0.5 0.6 0.5 1.0 6
playsound minecraft:entity.illusioner.prepare_mirror player @a ~ ~ ~ 0.6 1.3
execute as @e[type=minecraft:item_display,tag=pocket.fxkey,distance=..6] if score @s pocket.slot = #s pocket.tmp run data merge entity @s {start_interpolation:0,interpolation_duration:2,transformation:{left_rotation:{angle:3.142f,axis:[0f,1f,0f]},right_rotation:[0f,0f,0f,1f],translation:[0f,0f,0f],scale:[1.25f,1.25f,1.25f]}}
